In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [5]:
dataset=pd.read_csv("CKD.csv")
print("No of Columns:", dataset.shape[1])
print("No of Rows:", dataset.shape[0])
dataset

No of Columns: 25
No of Rows: 399

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [6]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
print("After converting categorical data,  No of Columns:", dataset.shape[1])
print("After converting categorical data,  No of Rows:", dataset.shape[0])
dataset

After converting categorical data,  No of Columns: 28
After converting categorical data,  No of Rows: 399

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

dependent=dataset[['classification_yes']]

In [8]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
param_grid = {
    'criterion':['gini', 'entropy', 'log_loss'],
     'max_features':[None,'sqrt','log2'],
    'splitter': ['best','random']
}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid, refit=True, verbose=3, n_jobs=-1,cv=5,scoring='f1_weighted')
grid.fit(X_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [11]:
re=grid.cv_results_
grid_prediction = grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_prediction)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test,grid_prediction)

from sklearn.metrics import f1_score
f1_macro = f1_score(y_test,grid_prediction,average='weighted')

print("Best Model {}:", format(grid.best_params_),f1_macro)

Best Model {}: {'criterion': 'gini', 'max_features': 'sqrt', 'splitter': 'random'} 0.9834018801410106

In [12]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9866666666666667

In [13]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.035501,0.007302,0.062410,0.008135,gini,None,best,"{'criterion': 'gini', 'max_features': None, 's...",0.911692,0.963889,0.894531,0.926743,0.944509,0.928273,0.024281,17
1,0.035692,0.006854,0.069603,0.009138,gini,None,random,"{'criterion': 'gini', 'max_features': None, 's...",0.929144,0.964286,0.947015,0.982221,0.981894,0.960912,0.020533,9
2,0.033595,0.008279,0.056524,0.009781,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.964572,0.910254,0.929513,0.909115,1.000000,0.942691,0.034975,11
3,0.024956,0.004946,0.060276,0.009634,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.982221,1.000000,0.982051,0.982221,0.981894,0.985677,0.007162,1
4,0.032367,0.009544,0.069440,0.007173,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.982221,0.946153,0.964572,0.945469,0.981728,0.964029,0.016177,8
5,0.028249,0.006235,0.068169,0.006480,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.982051,0.982221,0.982221,0.963247,0.981948,0.011626,2
6,0.038461,0.008402,0.058659,0.009402,entropy,None,best,"{'criterion': 'entropy', 'max_features': None,...",0.982051,0.963889,0.859355,0.909115,0.963636,0.935609,0.045296,14
7,0.028471,0.005617,0.065653,0.011900,entropy,None,random,"{'criterion': 'entropy', 'max_features': None,...",0.982221,0.928571,1.000000,0.982051,0.981894,0.974947,0.024207,4
8,0.026835,0.004379,0.057193,0.004551,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.929144,0.893717,0.910254,0.964286,0.945185,0.928517,0.024909,16
9,0.034697,0.005099,0.054761,0.005119,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.982221,0.982051,0.964286,0.964286,1.000000,0.978569,0.013362,3
10,0.028825,0.006679,0.063520,0.008916,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.946663,0.910254,0.911692,0.946663,0.981728,0.939400,0.026512,12
11,0.033671,0.007789,0.064368,0.008473,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.982221,0.963889,0.964286,0.945469,0.981894,0.967552,0.013657,7
12,0.037014,0.009363,0.065624,0.008057,log_loss,None,best,"{'criterion': 'log_loss', 'max_features': None...",1.000000,0.945469,0.859355,0.909115,0.981728,0.939133,0.050646,13
13,0.030089,0.005075,0.062764,0.010853,log_loss,None,random,"{'criterion': 'log_loss', 'max_features': None...",0.982221,0.946663,1.000000,0.964286,0.963912,0.971416,0.018186,5
14,0.027357,0.007934,0.063854,0.010687,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.982221,0.929144,0.894531,0.874356,0.981728,0.932396,0.044112,15
15,0.032419,0.008499,0.054111,0.005726,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.982221,0.947015,0.928571,0.946153,0.981894,0.957171,0.021360,10
16,0.031287,0.002763,0.068248,0.004205,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",0.929513,0.926743,0.894531,0.946663,0.927273,0.924944,0.016889,18
17,0.026392,0.003124,0.039788,0.008038,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",0.947015,0.982051,0.982051,0.964572,0.963912,0.967920,0.013143,6

In [14]:
Future_Predictions = grid.predict([[
    45,      # age
    80,      # bp
    1,       # al
    0,       # su
    121,     # bgr
    36,      # bu
    1.2,     # sc
    138,     # sod
    4.5,     # pot
    15.2,    # hrmo
    44,      # pcv
    7800,    # wc
    5.1,     # rc
    0,       # sg_b
    0,       # sg_c
    1,       # sg_d
    0,       # sg_e
    1,       # rbc_normal
    1,       # pc_normal
    0,       # pcc_present
    0,       # ba_present
    1,       # htn_yes
    1,       # dm_yes
    0,       # cad_yes
    1,       # appet_yes
    0,       # pe_yes
    0        # ane_yes
]])

print(Future_Predictions)

[1]

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(