In [2]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [3]:
dataset=pd.read_csv("CKD.csv")
print("No of Columns:", dataset.shape[1])
print("No of Rows:", dataset.shape[0])
dataset

No of Columns: 25
No of Rows: 399

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
print("No of Columns:", dataset.shape[1])
print("No of Rows:", dataset.shape[0])
dataset

No of Columns: 28
No of Rows: 399

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [5]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

dependent=dataset[['classification_yes']]

In [6]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid = {
    'n_estimators': [50, 100, 200],
    'criterion': ['gini', 'entropy', 'log_loss'],
  #  'max_depth': [None, 5, 10, 20],
    'max_features': ['sqrt', 'log2', None],
    'bootstrap': [True, False]
}
grid=GridSearchCV(RandomForestClassifier(),param_grid, refit=True, verbose=3, n_jobs=-1,cv=5,scoring='f1_weighted')
grid.fit(X_train,y_train)

Fitting 5 folds for each of 54 candidates, totalling 270 fits

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [50, 100, 200]},
             scoring='f1_weighted', verbose=3)

In [9]:

re=grid.cv_results_
grid_prediction = grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_prediction)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test,grid_prediction)

from sklearn.metrics import f1_score
f1_macro = f1_score(y_test,grid_prediction,average='weighted')

print("Best Model {}:", format(grid.best_params_),f1_macro)

Best Model {}: {'bootstrap': False, 'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 50} 0.9916474440062505

In [10]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0

In [11]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_bootstrap,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.757349,0.075730,0.101873,0.012649,True,gini,sqrt,50,"{'bootstrap': True, 'criterion': 'gini', 'max_...",1.000000,0.982051,0.947015,0.982051,1.000000,0.982223,0.019348,7
1,1.543489,0.236074,0.121325,0.018765,True,gini,sqrt,100,"{'bootstrap': True, 'criterion': 'gini', 'max_...",1.000000,0.946153,0.947015,0.982051,1.000000,0.975044,0.024146,27
2,2.578638,0.318254,0.089390,0.062974,True,gini,sqrt,200,"{'bootstrap': True, 'criterion': 'gini', 'max_...",1.000000,0.982051,0.947015,0.982051,0.981728,0.978569,0.017258,19
3,0.748298,0.099220,0.094031,0.029471,True,gini,log2,50,"{'bootstrap': True, 'criterion': 'gini', 'max_...",1.000000,0.945469,0.964572,0.982051,1.000000,0.978418,0.021081,24
4,1.293125,0.380564,0.076652,0.043765,True,gini,log2,100,"{'bootstrap': True, 'criterion': 'gini', 'max_...",1.000000,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,31
5,2.799855,0.729009,0.138857,0.071369,True,gini,log2,200,"{'bootstrap': True, 'criterion': 'gini', 'max_...",1.000000,0.982051,0.964572,0.982051,0.981728,0.982080,0.011205,13
6,1.054009,0.022804,0.108744,0.011870,True,gini,None,50,"{'bootstrap': True, 'criterion': 'gini', 'max_...",0.982221,0.945469,0.894531,0.926743,0.981728,0.946138,0.033492,40
7,2.074241,0.054396,0.136506,0.007780,True,gini,None,100,"{'bootstrap': True, 'criterion': 'gini', 'max_...",0.982051,0.928571,0.894531,0.926743,0.981728,0.942725,0.034194,41
8,4.172308,0.046324,0.191193,0.010411,True,gini,None,200,"{'bootstrap': True, 'criterion': 'gini', 'max_...",0.964286,0.945469,0.894531,0.945469,0.981728,0.946297,0.029189,37
9,0.905053,0.020555,0.110454,0.005940,True,entropy,sqrt,50,"{'bootstrap': True, 'criterion': 'entropy', 'm...",1.000000,0.945469,0.982221,0.964286,0.981728,0.974741,0.018488,34
10,1.642293,0.311425,0.094403,0.046089,True,entropy,sqrt,100,"{'bootstrap': True, 'criterion': 'entropy', 'm...",1.000000,0.982051,0.947015,0.982051,1.000000,0.982223,0.019348,7
11,2.392115,1.033805,0.107864,0.072439,True,entropy,sqrt,200,"{'bootstrap': True, 'criterion': 'entropy', 'm...",1.000000,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,20
12,0.928088,0.014340,0.111689,0.008723,True,entropy,log2,50,"{'bootstrap': True, 'criterion': 'entropy', 'm...",1.000000,0.963889,0.964572,0.982051,1.000000,0.982102,0.015998,10
13,1.601917,0.382829,0.121943,0.042505,True,entropy,log2,100,"{'bootstrap': True, 'criterion': 'entropy', 'm...",1.000000,0.963889,0.982221,0.982051,1.000000,0.985632,0.013491,5
14,3.538912,0.028739,0.197283,0.007988,True,entropy,log2,200,"{'bootstrap': True, 'criterion': 'entropy', 'm...",1.000000,0.963889,0.964572,0.982051,1.000000,0.982102,0.015998,10
15,1.097956,0.025028,0.111722,0.005351,True,entropy,None,50,"{'bootstrap': True, 'criterion': 'entropy', 'm...",1.000000,0.927778,0.894531,0.909115,0.981728,0.942630,0.041176,42
16,2.179053,0.039413,0.136552,0.005434,True,entropy,None,100,"{'bootstrap': True, 'criterion': 'entropy', 'm...",1.000000,0.927778,0.894531,0.926743,0.981728,0.946156,0.038844,38
17,4.294199,0.061692,0.195740,0.014128,True,entropy,None,200,"{'bootstrap': True, 'criterion': 'entropy', 'm...",1.000000,0.927778,0.894531,0.909115,0.981728,0.942630,0.041176,42
18,0.926131,0.015706,0.111051,0.002519,True,log_loss,sqrt,50,"{'bootstrap': True, 'criterion': 'log_loss', '...",1.000000,0.963889,0.912029,0.982051,0.981728,0.967939,0.030198,36
19,1.815083,0.016423,0.140750,0.004773,True,log_loss,sqrt,100,"{'bootstrap': True, 'criterion': 'log_loss', '...",1.000000,0.963889,0.947015,0.982051,1.000000,0.978591,0.020697,18
20,3.548940,0.029241,0.199913,0.007511,True,log_loss,sqrt,200,"{'bootstrap': True, 'criterion': 'log_loss', '...",1.000000,0.945469,0.947015,0.982051,1.000000,0.974907,0.024310,30
21,0.918217,0.010859,0.111903,0.002234,True,log_loss,log2,50,"{'bootstrap': True, 'criterion': 'log_loss', '...",1.000000,0.963889,0.947015,0.964286,1.000000,0.975038,0.021314,28
22,1.665603,0.315278,0.123100,0.043086,True,log_loss,log2,100,"{'bootstrap': True, 'criterion': 'log_loss', '...",1.000000,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,20
23,2.656188,0.603032,0.079695,0.053217,True,log_loss,log2,200,"{'bootstrap': True, 'criterion': 'log_loss', '...",1.000000,0.963889,0.929513,0.982051,1.000000,0.975090,0.026428,26
24,1.055331,0.128599,0.093697,0.033753,True,log_loss,None,50,"{'bootstrap': True, 'criterion': 'log_loss', '...",1.000000,0.927778,0.894531,0.926743,0.981728,0.946156,0.038844,38
25,1.876829,0.610446,0.113757,0.040822,True,log_loss,None,100,"{'bootstrap': True, 'criterion': 'log_loss', '...",0.982051,0.927778,0.894531,0.926743,0.981728,0.942566,0.034261,45
26,3.724162,1.114877,0.167877,0.060886,True,log_loss,None,200,"{'bootstrap': True, 'criterion': 'log_loss', '...",1.000000,0.927778,0.894531,0.909115,0.981728,0.942630,0.041176,42
27,0.720473,0.007354,0.110162,0.002646,False,gini,sqrt,50,"{'bootstrap': False, 'criterion': 'gini', 'max...",1.000000,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,31
28,1.400324,0.015260,0.138673,0.009806,False,gini,sqrt,100,"{'bootstrap': False, 'criterion': 'gini', 'max...",1.000000,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,9
29,2.729314,0.039560,0.198200,0.007322,False,gini,sqrt,200,"{'bootstrap': False, 'criterion': 'gini', 'max...",1.000000,0.982051,0.982221,0.964286,0.981728,0.982057,0.011295,17
30,0.698117,0.009088,0.106726,0.011196,False,gini,log2,50,"{'bootstrap': False, 'criterion': 'gini', 'max...",1.000000,0.963889,0.964572,0.982051,0.981728,0.978448,0.013362,23
31,1.376105,0.018008,0.140894,0.005650,False,gini,log2,100,"{'bootstrap': False, 'criterion': 'gini', 'max...",1.000000,0.963889,0.982221,0.964286,1.000000,0.982079,0.016061,14
32,2.631095,0.089408,0.169920,0.060879,False,gini,log2,200,"{'bootstrap': False, 'criterion': 'gini', 'max...",1.000000,0.963889,0.982221,0.964286,1.000000,0.982079,0.016061,14
33,0.903629,0.184515,0.078334,0.038978,False,gini,None,50,"{'bootstrap': False, 'criterion': 'gini', 'max...",0.929144,0.927778,0.894531,0.945469,0.981728,0.935730,0.028336,49
34,1.978378,0.092154,0.134450,0.002563,False,gini,None,100,"{'bootstrap': False, 'criterion': 'gini', 'max...",0.929144,0.909115,0.894531,0.945469,0.981728,0.931998,0.030299,52
35,3.880177,0.193471,0.190887,0.006635,False,gini,None,200,"{'bootstrap': False, 'criterion': 'gini', 'max...",0.929144,0.927778,0.894531,0.926743,0.981728,0.931985,0.028037,53
36,0.722667,0.013752,0.107746,0.007779,False,entropy,sqrt,50,"{'bootstrap': False, 'criterion': 'entropy', '...",1.000000,0.982051,0.964572,0.982051,1.000000,0.985735,0.013281,1
37,1.385029,0.027458,0.135629,0.004018,False,entropy,sqrt,100,"{'bootstrap': False, 'criterion': 'entropy', '...",1.000000,0.945469,0.982221,0.964286,1.000000,0.978395,0.021125,25
38,2.788773,0.039128,0.195319,0.007510,False,entropy,sqrt,200,"{'bootstrap': False, 'criterion': 'entropy', '...",1.000000,0.963889,0.947015,0.964286,1.000000,0.975038,0.021314,28
39,0.718968,0.011895,0.112073,0.005679,False,entropy,log2,50,"{'bootstrap': False, 'criterion': 'entropy', '...",1.000000,0.982051,0.982221,0.964286,1.000000,0.985712,0.013364,2
40,1.391365,0.032594,0.144872,0.011652,False,entropy,log2,100,"{'bootstrap': False, 'criterion': 'entropy', '...",1.000000,0.982051,0.982221,0.964286,1.000000,0.985712,0.013364,2
41,2.758144,0.012214,0.193340,0.005916,False,entropy,log2,200,"{'bootstrap': False, 'criterion': 'entropy', '...",1.000000,0.982051,0.982221,0.964286,1.000000,0.985712,0.013364,2
42,0.996036,0.061027,0.112087,0.004000,False,entropy,None,50,"{'bootstrap': False, 'criterion': 'entropy', '...",0.982051,0.945469,0.876984,0.909115,0.963636,0.935451,0.037890,50
43,1.828385,0.219508,0.117892,0.039885,False,entropy,None,100,"{'bootstrap': False, 'criterion': 'entropy', '...",0.982051,0.945469,0.876984,0.909115,0.963636,0.935451,0.037890,50
44,3.683403,0.185284,0.185743,0.004199,False,entropy,None,200,"{'bootstrap': False, 'criterion': 'entropy', '...",0.982051,0.945469,0.876984,0.909115,0.981728,0.939069,0.041134,46
45,0.668426,0.012192,0.101667,0.003626,False,log_loss,sqrt,50,"{'bootstrap': False, 'criterion': 'log_loss', ...",1.000000,0.945469,0.947015,0.964286,1.000000,0.971354,0.024305,35
46,1.341730,0.013464,0.137429,0.003783,False,log_loss,sqrt,100,"{'bootstrap': False, 'criterion': 'log_loss', ...",1.000000,0.963889,0.982221,0.964286,1.000000,0.982079,0.016061,14
47,2.568107,0.031755,0.194001,0.009264,False,log_loss,sqrt,200,"{'bootstrap': False, 'criterion': 'log_loss', ...",1.000000,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,31
48,0.663852,0.008448,0.104081,0.003682,False,log_loss,log2,50,"{'bootstrap': False, 'criterion': 'log_loss', ...",1.000000,0.963889,0.982221,0.982051,1.000000,0.985632,0.013491,5
49,1.405695,0.018846,0.134310,0.012402,False,log_loss,log2,100,"{'bootstrap': False, 'criterion': 'log_loss', ...",1.000000,0.963889,0.964572,0.982051,1.000000,0.982102,0.015998,10
50,2.408489,0.500691,0.166168,0.058812,False,log_loss,log2,200,"{'bootstrap': False, 'criterion': 'log_loss', ...",1.000000,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,20
51,0.980670,0.083198,0.100249,0.015504,False,log_loss,None,50,"{'bootstrap': False, 'criterion': 'log_loss', ...",1.000000,0.945469,0.876984,0.909115,0.963636,0.939041,0.042682,47
52,1.878919,0.040407,0.126650,0.013746,False,log_loss,None,100,"{'bootstrap': False, 'criterion': 'log_loss', ...",0.982051,0.926743,0.859355,0.909115,0.981728,0.931798,0.046490,54
53,2.722943,0.427769,0.081047,0.029560,False,log_loss,None,200,"{'bootstrap': False, 'criterion': 'log_loss', ...",1.000000,0.945469,0.876984,0.909115,0.963636,0.939041,0.042682,47

In [12]:
Future_Predictions = grid.predict([[
    45,      # age
    80,      # bp
    1,       # al
    0,       # su
    121,     # bgr
    36,      # bu
    1.2,     # sc
    138,     # sod
    4.5,     # pot
    15.2,    # hrmo
    44,      # pcv
    7800,    # wc
    5.1,     # rc
    0,       # sg_b
    0,       # sg_c
    1,       # sg_d
    0,       # sg_e
    1,       # rbc_normal
    1,       # pc_normal
    0,       # pcc_present
    0,       # ba_present
    1,       # htn_yes
    1,       # dm_yes
    0,       # cad_yes
    1,       # appet_yes
    0,       # pe_yes
    0        # ane_yes
]])

print(Future_Predictions)

[1]

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(