In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")
print("No of Columns:", dataset.shape[1])
print("No of Rows:", dataset.shape[0])
dataset

No of Columns: 25
No of Rows: 399

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
print("No of Columns:", dataset.shape[1])
print("No of Rows:", dataset.shape[0])
dataset

No of Columns: 28
No of Rows: 399

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
print("After converting categorical data,  No of Columns:", dataset.shape[1])
print("After converting categorical data,  No of Rows:", dataset.shape[0])
dataset

After converting categorical data,  No of Columns: 28
After converting categorical data,  No of Rows: 399

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [5]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

dependent=dataset[['classification_yes']]

In [6]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [7]:

from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size': [20, 30, 40, 50],
    'p': [1, 2]
}

grid=GridSearchCV(KNeighborsClassifier(),param_grid,refit=True,n_jobs=-1, cv=5, scoring='f1_weighted')
grid.fit(X_train,y_train)

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 7, 9, 11], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='f1_weighted')

In [8]:
re=grid.cv_results_
grid_prediction = grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_prediction)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test,grid_prediction)

from sklearn.metrics import f1_score
f1_macro = f1_score(y_test,grid_prediction,average='weighted')

print("Best Model {}:", format(grid.best_params_),f1_macro)

Best Model {}: {'algorithm': 'auto', 'leaf_size': 20, 'n_neighbors': 9, 'p': 1, 'weights': 'distance'} 0.7863636363636365

In [9]:

from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.8645925925925926

In [10]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_leaf_size,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015311,0.004112,0.302070,0.016826,auto,20,3,1,uniform,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.658966,0.770307,0.681034,0.753906,0.783471,0.729537,0.049995,145
1,0.015591,0.004712,0.219995,0.154899,auto,20,3,1,distance,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.697759,0.753205,0.714286,0.789032,0.783471,0.747551,0.036411,65
2,0.012790,0.001908,0.036196,0.003821,auto,20,3,2,uniform,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.566667,0.683548,0.699632,0.736088,0.764621,0.690111,0.067879,305
3,0.012372,0.001669,0.030883,0.001508,auto,20,3,2,distance,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.645722,0.700820,0.733254,0.771542,0.783471,0.726962,0.050007,177
4,0.011031,0.000542,0.032348,0.002520,auto,20,5,1,uniform,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.700900,0.701247,0.716475,0.753906,0.730070,0.720520,0.019893,209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,0.009499,0.000961,0.027286,0.003767,brute,50,9,2,distance,"{'algorithm': 'brute', 'leaf_size': 50, 'n_nei...",0.718050,0.736395,0.734970,0.736395,0.730070,0.731176,0.006962,129
316,0.010285,0.001077,0.031452,0.005031,brute,50,11,1,uniform,"{'algorithm': 'brute', 'leaf_size': 50, 'n_nei...",0.789032,0.824219,0.682692,0.753871,0.692197,0.748402,0.054600,49
317,0.009331,0.000921,0.027816,0.002650,brute,50,11,1,distance,"{'algorithm': 'brute', 'leaf_size': 50, 'n_nei...",0.771277,0.771542,0.733254,0.771542,0.766061,0.762735,0.014888,17
318,0.009771,0.001648,0.030035,0.002433,brute,50,11,2,uniform,"{'algorithm': 'brute', 'leaf_size': 50, 'n_nei...",0.753906,0.735075,0.648387,0.700900,0.728409,0.713335,0.036657,241
319,0.008831,0.001322,0.027475,0.000640,brute,50,11,2,distance,"{'algorithm': 'brute', 'leaf_size': 50, 'n_nei...",0.718050,0.718750,0.716475,0.753871,0.728409,0.727111,0.014021,161

In [11]:
Future_Predictions = grid.predict([[
    45,      # age
    80,      # bp
    1,       # al
    0,       # su
    121,     # bgr
    36,      # bu
    1.2,     # sc
    138,     # sod
    4.5,     # pot
    15.2,    # hrmo
    44,      # pcv
    7800,    # wc
    5.1,     # rc
    0,       # sg_b
    0,       # sg_c
    1,       # sg_d
    0,       # sg_e
    1,       # rbc_normal
    1,       # pc_normal
    0,       # pcc_present
    0,       # ba_present
    1,       # htn_yes
    1,       # dm_yes
    0,       # cad_yes
    1,       # appet_yes
    0,       # pe_yes
    0        # ane_yes
]])

print(Future_Predictions)

[0]

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(