In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")
print("No of Columns:", dataset.shape[1])
print("No of Rows:", dataset.shape[0])
dataset

No of Columns: 25
No of Rows: 399

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
print("No of Columns:", dataset.shape[1])
print("No of Rows:", dataset.shape[0])
dataset

No of Columns: 28
No of Rows: 399

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

dependent=dataset[['classification_yes']]

In [5]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB

param_grid = {
    'alpha': [0.001, 0.01, 0.1, 0.5, 1, 2, 5, 10],
    'fit_prior': [True, False],
    'force_alpha': [True, False]
}
grid=GridSearchCV(MultinomialNB(),param_grid,refit=True,n_jobs=-1, cv=5, scoring='f1_weighted')
grid.fit(X_train,y_train)

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=5, estimator=MultinomialNB(), n_jobs=-1,
             param_grid={'alpha': [0.001, 0.01, 0.1, 0.5, 1, 2, 5, 10],
                         'fit_prior': [True, False],
                         'force_alpha': [True, False]},
             scoring='f1_weighted')

In [7]:
re=grid.cv_results_
grid_prediction = grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_prediction)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test,grid_prediction)

from sklearn.metrics import f1_score
f1_macro = f1_score(y_test,grid_prediction,average='weighted')

print("Best Model {}:", format(grid.best_params_),f1_macro)

Best Model {}: {'alpha': 0.001, 'fit_prior': True, 'force_alpha': True} 0.9014285714285715

In [8]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9525925925925927

In [9]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_fit_prior,param_force_alpha,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.056669,0.011144,0.059875,0.014091,0.001,True,True,"{'alpha': 0.001, 'fit_prior': True, 'force_alp...",0.929513,0.893717,0.964572,0.947015,0.927824,0.932528,0.023555,1
1,0.060307,0.026499,0.069942,0.011868,0.001,True,False,"{'alpha': 0.001, 'fit_prior': True, 'force_alp...",0.929513,0.893717,0.964572,0.947015,0.927824,0.932528,0.023555,1
2,0.031489,0.004539,0.057681,0.006716,0.001,False,True,"{'alpha': 0.001, 'fit_prior': False, 'force_al...",0.929513,0.893717,0.964572,0.947015,0.927824,0.932528,0.023555,1
3,0.035058,0.002275,0.055390,0.007197,0.001,False,False,"{'alpha': 0.001, 'fit_prior': False, 'force_al...",0.929513,0.893717,0.964572,0.947015,0.927824,0.932528,0.023555,1
4,0.043432,0.008221,0.066556,0.004690,0.010,True,True,"{'alpha': 0.01, 'fit_prior': True, 'force_alph...",0.912029,0.876368,0.929513,0.894531,0.927824,0.908053,0.020268,5
5,0.042046,0.005752,0.069391,0.001092,0.010,True,False,"{'alpha': 0.01, 'fit_prior': True, 'force_alph...",0.912029,0.876368,0.929513,0.894531,0.927824,0.908053,0.020268,5
6,0.041352,0.010927,0.070285,0.002175,0.010,False,True,"{'alpha': 0.01, 'fit_prior': False, 'force_alp...",0.894531,0.876368,0.929513,0.894531,0.927824,0.904553,0.020783,7
7,0.046791,0.008315,0.073943,0.008686,0.010,False,False,"{'alpha': 0.01, 'fit_prior': False, 'force_alp...",0.894531,0.876368,0.929513,0.894531,0.927824,0.904553,0.020783,7
8,0.041749,0.007793,0.081280,0.004174,0.100,True,True,"{'alpha': 0.1, 'fit_prior': True, 'force_alpha...",0.859355,0.841653,0.894531,0.894531,0.892243,0.876463,0.021938,9
9,0.048025,0.008894,0.076833,0.009576,0.100,True,False,"{'alpha': 0.1, 'fit_prior': True, 'force_alpha...",0.859355,0.841653,0.894531,0.894531,0.892243,0.876463,0.021938,9
10,0.055525,0.002452,0.077927,0.004566,0.100,False,True,"{'alpha': 0.1, 'fit_prior': False, 'force_alph...",0.859355,0.841653,0.894531,0.894531,0.892243,0.876463,0.021938,9
11,0.051769,0.012260,0.076267,0.003125,0.100,False,False,"{'alpha': 0.1, 'fit_prior': False, 'force_alph...",0.859355,0.841653,0.894531,0.894531,0.892243,0.876463,0.021938,9
12,0.048009,0.007135,0.073015,0.008220,0.500,True,True,"{'alpha': 0.5, 'fit_prior': True, 'force_alpha...",0.841610,0.841653,0.876984,0.859355,0.874447,0.858810,0.015266,13
13,0.050405,0.004307,0.077302,0.002526,0.500,True,False,"{'alpha': 0.5, 'fit_prior': True, 'force_alpha...",0.841610,0.841653,0.876984,0.859355,0.874447,0.858810,0.015266,13
14,0.048574,0.009044,0.077306,0.005932,0.500,False,True,"{'alpha': 0.5, 'fit_prior': False, 'force_alph...",0.841610,0.841653,0.876984,0.859355,0.874447,0.858810,0.015266,13
15,0.046415,0.002616,0.078247,0.005461,0.500,False,False,"{'alpha': 0.5, 'fit_prior': False, 'force_alph...",0.841610,0.841653,0.876984,0.859355,0.874447,0.858810,0.015266,13
16,0.049542,0.001628,0.074676,0.006815,1.000,True,True,"{'alpha': 1, 'fit_prior': True, 'force_alpha':...",0.841610,0.841653,0.876984,0.859355,0.856598,0.855240,0.013130,17
17,0.051086,0.002742,0.076352,0.005154,1.000,True,False,"{'alpha': 1, 'fit_prior': True, 'force_alpha':...",0.841610,0.841653,0.876984,0.859355,0.856598,0.855240,0.013130,17
18,0.050484,0.004648,0.074984,0.008879,1.000,False,True,"{'alpha': 1, 'fit_prior': False, 'force_alpha'...",0.823718,0.841653,0.876984,0.859355,0.856598,0.851662,0.017921,19
19,0.049121,0.008250,0.060430,0.009979,1.000,False,False,"{'alpha': 1, 'fit_prior': False, 'force_alpha'...",0.823718,0.841653,0.876984,0.859355,0.856598,0.851662,0.017921,19
20,0.050556,0.005910,0.076723,0.008701,2.000,True,True,"{'alpha': 2, 'fit_prior': True, 'force_alpha':...",0.823718,0.824219,0.876984,0.823718,0.856598,0.841047,0.021987,21
21,0.048409,0.003395,0.076023,0.008752,2.000,True,False,"{'alpha': 2, 'fit_prior': True, 'force_alpha':...",0.823718,0.824219,0.876984,0.823718,0.856598,0.841047,0.021987,21
22,0.054537,0.005094,0.071307,0.008724,2.000,False,True,"{'alpha': 2, 'fit_prior': False, 'force_alpha'...",0.823718,0.824219,0.876984,0.805644,0.856598,0.837433,0.025709,23
23,0.046863,0.007265,0.080669,0.005412,2.000,False,False,"{'alpha': 2, 'fit_prior': False, 'force_alpha'...",0.823718,0.824219,0.876984,0.805644,0.856598,0.837433,0.025709,23
24,0.050815,0.010047,0.081807,0.008984,5.000,True,True,"{'alpha': 5, 'fit_prior': True, 'force_alpha':...",0.805644,0.789032,0.876984,0.787356,0.856598,0.823123,0.036793,25
25,0.050134,0.007042,0.077568,0.006849,5.000,True,False,"{'alpha': 5, 'fit_prior': True, 'force_alpha':...",0.805644,0.789032,0.876984,0.787356,0.856598,0.823123,0.036793,25
26,0.051155,0.002980,0.077659,0.003891,5.000,False,True,"{'alpha': 5, 'fit_prior': False, 'force_alpha'...",0.805644,0.771215,0.876984,0.787356,0.856598,0.819560,0.040589,27
27,0.050732,0.007647,0.081552,0.006922,5.000,False,False,"{'alpha': 5, 'fit_prior': False, 'force_alpha'...",0.805644,0.771215,0.876984,0.787356,0.856598,0.819560,0.040589,27
28,0.048598,0.005968,0.076263,0.005365,10.000,True,True,"{'alpha': 10, 'fit_prior': True, 'force_alpha'...",0.787356,0.771215,0.876984,0.768820,0.856598,0.812195,0.045491,29
29,0.050443,0.005948,0.080001,0.002691,10.000,True,False,"{'alpha': 10, 'fit_prior': True, 'force_alpha'...",0.787356,0.771215,0.876984,0.768820,0.856598,0.812195,0.045491,29
30,0.046064,0.004275,0.067832,0.007089,10.000,False,True,"{'alpha': 10, 'fit_prior': False, 'force_alpha...",0.787356,0.771215,0.876984,0.768820,0.856598,0.812195,0.045491,29
31,0.043860,0.003611,0.058960,0.005558,10.000,False,False,"{'alpha': 10, 'fit_prior': False, 'force_alpha...",0.787356,0.771215,0.876984,0.768820,0.856598,0.812195,0.045491,29

In [10]:
Future_Predictions = grid.predict([[
    45,      # age
    80,      # bp
    1,       # al
    0,       # su
    121,     # bgr
    36,      # bu
    1.2,     # sc
    138,     # sod
    4.5,     # pot
    15.2,    # hrmo
    44,      # pcv
    7800,    # wc
    5.1,     # rc
    0,       # sg_b
    0,       # sg_c
    1,       # sg_d
    0,       # sg_e
    1,       # rbc_normal
    1,       # pc_normal
    0,       # pcc_present
    0,       # ba_present
    1,       # htn_yes
    1,       # dm_yes
    0,       # cad_yes
    1,       # appet_yes
    0,       # pe_yes
    0        # ane_yes
]])

print(Future_Predictions)

[1]

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(